trigger:
- main

pool:
  name: my-self-agent

steps:
- script: echo "Code pulled successfully"
  displayName: "CI Step"

- script: echo "Build step running"
  displayName: "Build Step"

- script: echo "Running SonarQube Scan..."
  displayName: "SonarQube Analysis"

- script: echo "Checking Quality Gate..."
  displayName: "Quality Gate"

- script: if not exist C:\deploy-folder mkdir C:\deploy-folder
  displayName: "Create Deployment Folder"

- script: echo "Hello from CD" > C:\deploy-folder\app.txt
  displayName: "Deploy Step"